begin remote
  name  AUN_ET30
  bits           16
  flags           SPACE_ENC|CONST_LENGTH
  eps             30
  aeps           100
  header       8889  4513
  one           563  1703
  zero          563   563
  ptrail        563
  gap          64464
  toggle_bit_mask 0x0
  begin codes
    FORWARD      0x0082
    MUTE         0x0088
    VOLUME+      0x008C
    MENU         0x0091
    PLAY_PAUSE   0x0093
    CIMA         0x0095
    INPUT        0x0097
    REWIND       0x0098
    DIREITA      0x0099
    BAIXO        0x009A
    ESQUERDA     0x009B
    VOLUME-      0x009C
    OK           0x009E
    VOLTAR       0x00A4
    POWER        0x00A8
  end codes
end remote
